### ISSUE TITLE
Hard difficulty takes long to load after starting a new game

### ISSUE THREAD

**Issue by jxe162** [ericcheng13/Software-Engineering#3]
After playing a game and returning to the new game screen, selecting the hard difficulty results in a lag of like a minute

**Comment by ericcheng13** [comment]
The hard difficulty does this because it is running through the remove everything algorithm. Does this because it has to check every spot and that takes a while. We can make it so it doesn't remove every spot which will reduce the lag time but this will reduce the difficulty of the puzzle
