### ISSUE TITLE
Make permanent cells red if interferes with inputted value

### ISSUE THREAD

**Issue by jxe162** [ericcheng13/Software-Engineering#5]
This can help players realize where exactly the issue with their inputted numbers is. It would still not allow players to edit, so it should be a different color red than the error red for inputted values.

**Comment by ericcheng13** [comment]
Working to get this to work. Check method implemented. Need to link with GUI to cause it to turn red.

**Comment by jxe162** [comment]
some cells turn red automatically, but others don't unless you click/highlight them. Probably has to do with not all cells refreshing when one is changed. Still needs more work.
